# 1. Ingestion des fichiers logs générés par Rsyslog
<source>
  @type tail
  path /var/log/remote/*/*.log
  pos_file /fluentd/etc/rsyslog.pos
  tag rsyslog.raw
  <parse>
    @type none
  </parse>
</source>

# 2. Parsing Regex de l'en-tête Syslog
<filter rsyslog.raw>
  @type parser
  key_name message
  reserve_data true
  <parse>
    @type regexp
    expression /^(?<log_time>\S+)\s+(?<hostname>\S+)\s+(?<program>[\w\-\._]+)(?:\[(?<pid>\d+)\])?:\s+(?<log_message>.*)$/
    time_format %Y-%m-%dT%H:%M:%S%z
  </parse>
</filter>

# 3. Extraction dynamique des champs spécifiques (SSH & FIM)
<filter rsyslog.raw>
  @type record_transformer
  enable_ruby true
  <record>
    src_ip ${record["log_message"] =~ /(?:from|by)\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/ ? $1 : nil}
    target_file ${record["log_message"] =~ /(\/etc\/[^\s:]+)/ ? $1 : nil}
  </record>
</filter>

# 4. Expédition des logs JSON structurés vers Loki
<match rsyslog.raw>
  @type loki
  url "http://soc-loki:3100"
  extra_labels {"job":"rsyslog", "env":"soc"}

  <label>
    program $.program
    hostname $.hostname
  </label>

  <buffer>
    @type memory
    flush_interval 2s
  </buffer>
</match>