module(load="imudp")
input(type="imudp" port="514")

module(load="imtcp")
input(type="imtcp" port="514")

# Template dynamique
template(name="RemoteLogs" type="string" string="/var/log/remote/%FROMHOST-IP%/%PROGRAMNAME%.log")

# On autorise rsyslog à créer les dossiers parents dynamiquement
*.* action(
    type="omfile" 
    DynaFile="RemoteLogs"
    CreateDirs="on"
    DirCreateMode="0755"
    FileCreateMode="0644"
)