# Chargement des modules de base
module(load="imuxsock") # Socket local
module(load="imfile")   # Surveillance de fichiers (FIM)

# Déclaration du fichier à surveiller
input(type="imfile"
      File="/etc/passwd"
      Tag="fim_passwd"
      Severity="notice"
      Facility="auth"
      StateFile="stat_passwd")

# Transfert de TOUS les logs vers le serveur central
*.* @__SYSLOG_SERVER_IP__:514